---
- name: "dokku apps:create {{ telegram_bot_app_name }}"
  dokku_app:
    app: "{{ telegram_bot_app_name }}"

- name: "dokku config:set {{ telegram_bot_app_name }}"
  dokku_config:
    app: "{{ telegram_bot_app_name }}"
    config:
      DOKKU_LETSENCRYPT_EMAIL: "admin@{{ dokku_hostname }}"
      PORT: "5000"
      APP_ENV: "production"
      APP_URL: "https://{{ telegram_bot_app_name }}.{{ dokku_hostname }}/"

- name: "dokku config:set TELEGRAM_TOKEN {{ telegram_bot_app_name }}"
  dokku_config:
    app: "{{ telegram_bot_app_name }}"
    config:
      TELEGRAM_TOKEN: "{{ TELEGRAM_TOKEN }}"
  when: TELEGRAM_TOKEN != ""

- name: "dokku clone {{ telegram_bot_app_name }}"
  dokku_clone:
    app: "{{ telegram_bot_app_name }}"
    repository: "{{ telegram_bot_repo }}"

- name: "dokku domains:set {{ telegram_bot_app_name }}"
  dokku_domains:
    app: "{{ telegram_bot_app_name }}"
    domains:
      - "{{ telegram_bot_app_name }}.{{ dokku_hostname }}"

- name: "Enable the letsencrypt plugin {{ telegram_bot_app_name }}"
  dokku_letsencrypt:
    app: "{{ telegram_bot_app_name }}"